### ISSUE TITLE
[BUG]: Unable to create custom steps by extending `BaseStep`

### ISSUE THREAD

**Issue by raghumulukutla** [zenml-io/zenml#627]
### Contact Details [Optional]

raghu.tjm@gmail.com

### System Information

ZenML version: 0.8.0
Install path: /Users/-/Library/Caches/pypoetry/virtualenvs/medical-imaging-pipeline-mXFg84T2-py3.7/lib/python3.7/site-packages/zenml
Python version: 3.7.6
Platform information: {'os': 'mac', 'mac_version': '10.16'}
Environment: native
Integrations: ['pytorch', 'scipy', 'sklearn']

### What happened?

Cannot create a custom steps by extending`BaseStep` API such as `BaseAnalyzerConfig` ,  with custom argument types as the verification of input argument types fails in the 'BaseStep`  metaclass

the error seems to be originating from here (line 137, `base_step.py`):

```
            **if issubclass(arg_type, BaseStepConfig):**
                # Raise an error if we already found a config in the signature
                if cls.CONFIG_CLASS is not None:
                    raise StepInterfaceError(
                        f"Found multiple configuration arguments "
                        f"('{cls.CONFIG_PARAMETER_NAME}' and '{arg}') when "
                        f"trying to create step '{name}'. Please make sure to "
                        f"only have one `BaseStepConfig` subclass as input "
                        f"argument for a step."
                    )
                cls.CONFIG_PARAMETER_NAME = arg
                cls.CONFIG_CLASS = arg_type
```

`arg_type` is set to string `TypeBuiltDataset` which is my custom step's argument type instead of a class 

### Reproduction steps

1. Extending `BaseStep` to create a custom `Step` (using class-based API)

```
class PreprocessComponent(BaseStep):
    """
    Base class for data preprocessing

    """

    @abstractmethod
    def entrypoint(
        self,
        dataset: TypeBuiltDataset,
    ) -> Output(dataset=TypeBuiltDataset):
        """
        Base entry point for data preprocessing
        """
        raise NotImplementedError
```

2. Specify custom arguments in the entrypoint (`TypeBuildDataset`)

### Relevant log output

```shell
Traceback (most recent call last):
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/-/workstation/repo/medical-imaging-pipeline/src/applications/ultrasound/features/ingest.py", line 18, in <module>
    from src.pipeline.component import IngestComponent
  File "/Users/-/workstation/repo/medical-imaging-pipeline/src/pipeline/component.py", line 75, in <module>
    class PreprocessComponent(BaseStep):
  File "/Users/-/Library/Caches/pypoetry/virtualenvs/medical-imaging-pipeline-mXFg84T2-py3.7/lib/python3.7/site-packages/zenml/steps/base_step.py", line 137, in __new__
    if issubclass(arg_type, BaseStepConfig):
  File "/Users/-/opt/anaconda3/envs/py376/lib/python3.7/abc.py", line 143, in __subclasscheck__
    return _abc_subclasscheck(cls, subclass)
TypeError: issubclass() arg 1 must be a class
```

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by schustmi** [comment]
Hi @raghumulukutla!
We rely on type annotations inside steps to find the right classes to read/write the artifacts that are passed between steps. Can you show us the code that `TypeBuiltDataset` is referring to, maybe we can figure out a way to support this data type?

**Comment by raghumulukutla** [comment]
It's a pretty complex annotation. 

```TypeBuiltDataset = Union[LazyDataset, Tuple[LazyDataset, ...]]```

`LazyDataset` however is an instance of `dict`

The thing is that  I am planning to write a `Materializer` for read/writing artifacts myself. Seems like we are restricted to basic types (`int`, `float`, `str`) at the moment while specifying arguments for custom steps?

**Comment by raghumulukutla** [comment]
Moreover, I get the same error trying to do something simple:

```
class IngestConfig(BaseStepConfig):
    """
    Base class for data ingestion config
    """


class IngestComponent(BaseStep):
    """
    Base class for data ingestion

    """

    @abstractmethod
    def entrypoint(
        self,
        config: IngestConfig,
        context: StepContext,
    ) -> Output(dataset=TypeBuiltDataset):
        """
        Base entry point for data ingestion
        """
        raise NotImplementedError
```

With the code above, the `BaseMetaClass` tries to check 'IngestConfig` is  an instance of `BaseConfig` and fails because the former of type `str` and not `class`

For comparison this is the code in`base_analyzer.py`, a built-in step:

```
class BaseAnalyzerConfig(BaseStepConfig):
    """Base class for analyzer step configurations"""


class BaseAnalyzerStep(BaseStep):
    """Base step implementation for any analyzer step implementation on ZenML"""

    @abstractmethod
    def entrypoint(  # type: ignore[override]
        self,
        dataset: DataArtifact,
        config: BaseAnalyzerConfig,
        context: StepContext,
    ) -> Output(  # type:ignore[valid-type]
        statistics=StatisticsArtifact, schema=SchemaArtifact
    ):
        """Base entrypoint for any analyzer implementation"""
``

**Comment by htahir1** [comment]
> Seems like we are restricted to basic types (int, float, str) at the moment while specifying arguments for custom steps?

You can pass natively json-able types as config parameters, so it's a bit more than int float and strings. If your `LazyDataset` is an instance of a dict it might work as a config parameter rather than an artifact. We should definitely make this clearer in the docs.

However, back to the original query: IMO having a complex data type with a `Union` is not the way we intended materializers to recognize this types. Rather, you should have your materializer have multiple `ASSOCIATED_TYPES` to cover the union case at the materializer level. Perhaps unfurling the Union and just writing a materializer for the raw 

I'm a bit confused by your second comment though: Can you share exactly what the error emssage is when you try to write this `IngestConfig`? It sounds to me that the `IngestComponent` might be the one at fault here due to output being equal to `TypeBuiltDataset`?

**Comment by schustmi** [comment]
As @htahir already mentioned, the config parameters are at the moment limited to json-serializable data types as ZenML, however the actual step inputs and outputs allow you any custom **class**. Can you explain a little the motiviation of passing a `dict` instance as the type annotation? That would mean your actual inputs/outputs returned from the step would be an instance of an instance of a dict?

**Comment by schustmi** [comment]
Regarding the `Union` type: Those are currently not supported as step inputs/outputs as well as associated types for a materializer, implementing the type validation and logic to find the correct materializer should be possible though.
I personally always thought it was desirable to have the signatures of my pipeline steps clearly defined, I'm guessing in your case the step dynamically receives data from somewhere and therefore doesn't know in advance what the output would be?

I'll just leave this here as a potential temporary solution while we figure out the best way to handle this: You could always annotate your step input/output with a simple `Tuple` annotation instead of `TypeBuiltDataset` and return a single-element tuple in case there is just one dict. (This would obviously still require a custom materializer that actually takes care of writing/reading these tuples)

**Comment by htahir1** [comment]
Perfect! Closing now as its solved
