### ISSUE TITLE
[FEATURE]: Manage poetry lock file in repository

### ISSUE THREAD

**Issue by anencore94** [zenml-io/zenml#645]
### Describe the feature you'd like

It tooks so long time to setup python environment at first. (took 600 seconds for resolving dependency versions in my env)
![image](https://user-images.githubusercontent.com/37469330/170273829-b05bbe5b-074e-44b9-be21-2096c0402199.png)

I saw at github action workflow, it uses cache to reduce `poetry install` time, but is there any reason for not managing poetry.lock file in github repo?

**Comment by htahir1** [comment]
@anencore94 The reason we dont commit the `poetry.lock` file is that on the [poetry docs](https://python-poetry.org/docs/basic-usage/#commit-your-poetrylock-file-to-version-control) it is recommended not to do so if you are building a library. I think the reasoning is that you want to be able to test your library in different dependency resolution scenarios because when it is published on pypi, the same will happen to the consumers of the package (i.e. our users who do `pip install zenml`. If we commit the .lock file then we are `locked in` ;-) to a certain set of dependencies which might be not reflected in the final package.

**Comment by anencore94** [comment]
@htahir1 I understand. Thanks for your explanation :)
