### ISSUE TITLE
[FEATURE]: Output protocols - Allow capturing specific types of zenml.steps.Output signatures

### ISSUE THREAD

**Issue by strangemonad** [zenml-io/zenml#686]
## Checks

* [x] I added a descriptive title to this issue
* [x] I have searched (google, github) for similar issues and couldn't find anything
* [x] I have read and followed [the docs](https://docs.zenml.io/) and still think this is a bug

## General

zenml 0.8.1

This probably relates to `TODO [ENG-161]`

**Problem**

The flexibility of `Output` in general is great but as you production-ize certain pipeline steps, you want to be able to better document what outputs you expect a step to produce so other steps and pipelines can depend on that artifact. It's also convenient to share that signature definition.

e.g. I want to capture that a train-test-split function always returns a `SplitOutput(train: DataArtifact, test: DataArtifact, validate: DataArtifact)` 

We probably don't want to json serialize the entire `@dataclass` or pydantic models here for the same reasons `Output` iterates over each field to produce an artifact. Some of the artifacts might be better serialized into different formats.

**Option 1**

One approach is for his would to work similar to a typed `NamedTuple` e.g.

```
class SplitOutput(Output):
    train: DataArtifact
    test: DataArtifact
    validate: DataArtifact
```

This should also handle record-widening subtype relationships e.g. if I have a SplitOutput subclass, it should be a valid return type to a step requiring a `SplitOutput` but the component generated by `generate_component_class` should have an output spec that has all fields.

```
class PartitionFactor(BaseModel):
    ...

class MyCustomSplitOutput(SplitOutput):
     learned_partition_factor: PartitionFactor
```

That way the train, test, validate data artifacts can be efficiently recorded (e.g. DataFrame -> Apache Arrow) and the pydantic `PartitionFactor` object can become json

**Option 2**

Introduce a `Protocol` that indicates this object should be treated as an `Output` where each field is a unique attribute. The protocol should be sufficient to yield the results of `Output.items` used by `BaseStepMeta` to configure `OUTPUT_SIGNATURE`

This approach allows the implementation of `Output` to change (e.g. move away from using `NamedTuple` entirely).

e.g.
```
@dataclass
class SplitOutput(OutputArtifacts)
    ...
```

Ideally this would also interoperate with `Output` e.g. if I have  an abstract base step `SplitterStep` that returns `SplitOutput`, a `@step def my_split() -> Output(train: ...): ...` function is one such function that satisfied the `SplitterStep` output signature spec because
- Output would be made to conform to the `OutputArtifacts` protocol and (used as the type marker in `BaseStepMeta` to distinguish single vs multiple return artifacts
- The Output named tuple has all the required fields (structural sub-typing agrees with the signature).

[ENG-161]: https://zenml.atlassian.net/browse/ENG-161?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by schustmi** [comment]
Hi @strangemonad,

thank you for the detailed suggestion/description! I have a few questions to make sure I understood your request/issue correctly.

The motivation behind all of that would be to have reusable definitions of specific `Outputs` that you could use in many different steps, correct? And the two options would then be to either
- allow subclassing of our `Output` class
- introduce an abstract base class from which both the standard `Output` as well as custom output definitions could inherit


> This should also handle record-widening subtype relationships e.g. if I have a SplitOutput subclass, it should be a valid return type to a step requiring a SplitOutput but the component generated by generate_component_class should have an output spec that has all fields.

This part is most confusing to me: Currently the `Output` class is used only as a type annotation, but the actual return value of a step is a normal `Tuple`. Internally we map the elements of this tuple to the names and types specified in the `Output` type annotation.
```python
@step
def s() -> Output(a=int, b=str):
    return 0, "b"  # <- We don't return an instance of `Output` here, but instead just a normal tuple
```
To detect that these output elements now refer to a `MyCustomSplitOutput` which is a subclass of `SplitOutput`, I think we would have to change the syntax of ZenML steps to:
```python
@step
def s() -> SplitOutput:
    return MyCustomSplitOutput(0, "b")
```
I personally prefer the current syntax without any custom return object, as they allow you to write ZenML steps exactly like you'd write a common python function, but if there's any major benefits we gain from the explicit return object I'm happy to change my opinion. 
You mention as one benefit from this that the different types could be serialized in different ways, but I think is even possible with our current implementation due to the different `Materializers` used for each datatype.

**Comment by strangemonad** [comment]
Hello, just so you know. I'm still thinking of how to explain this need more clearly with a set of motivating examples. I'm fairly familiar with Argo Pipelines, KF Pipelines and programing language and type theory but still somewhat new to how zenml attempts to wrap this neatly atop TFX and MLMD with outputs, artifact types and materializers.

In particular, I think there could be. A much cleaner and intuitive way of expressing the following code snippet from the `Standardized Artifacts` article in the docs but I'm still piecing together a more coherent design proposal

```python
@step(output_types={"output_1": SchemaArtifact})
def any_step() -> Output(
    output_1=pd.DataFrame, 
    output_2=pd.DataFrame
):
    ...
    return output_1, output_2
```

**Comment by htahir1** [comment]
Curious to hear your thoughts

**Comment by schustmi** [comment]
Closing this as we now use standard python type annotations for steps.
